// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo"
	"virtual-travel/domain/repository"
	"virtual-travel/infrastructure"
	"virtual-travel/infrastructure/database"
	"virtual-travel/interfaces/controllers"
	"virtual-travel/usecase"
	"virtual-travel/usecase/interactor"
)

// Injectors from wire.go:

func Initialize(e *echo.Echo, db *gorm.DB) *infrastructure.Router {
	userRepository := database.NewUserRepository(db)
	favoriteRepository := database.NewFavoriteRepository(db)
	favoriteInteractor := interactor.NewFavoriteInteractor(userRepository, favoriteRepository)
	linebotController := controllers.NewLinebotController(favoriteInteractor)
	router := infrastructure.NewRouter(e, db, linebotController)
	return router
}

// wire.go:

var superSet = wire.NewSet(database.NewFavoriteRepository, wire.Bind(new(repository.IFavoriteRepository), new(*database.FavoriteRepository)), database.NewUserRepository, wire.Bind(new(repository.IUserRepository), new(*database.UserRepository)), interactor.NewFavoriteInteractor, wire.Bind(new(usecase.IFavoriteUseCase), new(*interactor.FavoriteInteractor)), controllers.NewLinebotController, infrastructure.NewRouter)
