// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo"
	"virtual-travel/domain/repository"
	"virtual-travel/infrastructure"
	"virtual-travel/infrastructure/database"
	"virtual-travel/interfaces/controllers"
	"virtual-travel/interfaces/gateway"
	"virtual-travel/interfaces/presenter"
	"virtual-travel/usecases/igateway"
	"virtual-travel/usecases/interactor"
	"virtual-travel/usecases/interactor/usecase"
	"virtual-travel/usecases/ipresenter"
)

// Injectors from wire.go:

func Initialize(e *echo.Echo, db *gorm.DB) *infrastructure.Router {
	userRepository := database.NewUserRepository(db)
	favoriteRepository := database.NewFavoriteRepository(db)
	googleMapGateway := gateway.NewGoogleMapGateway()
	linePresenter := presenter.NewLinePresenter()
	favoriteInteractor := interactor.NewFavoriteInteractor(userRepository, favoriteRepository, googleMapGateway, linePresenter)
	searchInteractor := interactor.NewSearchInteractor(googleMapGateway, linePresenter)
	linebotController := controllers.NewLinebotController(favoriteInteractor, searchInteractor)
	router := infrastructure.NewRouter(e, linebotController)
	return router
}

// wire.go:

var superSet = wire.NewSet(database.NewFavoriteRepository, wire.Bind(new(repository.IFavoriteRepository), new(*database.FavoriteRepository)), database.NewUserRepository, wire.Bind(new(repository.IUserRepository), new(*database.UserRepository)), gateway.NewGoogleMapGateway, wire.Bind(new(igateway.IGoogleMapGateway), new(*gateway.GoogleMapGateway)), presenter.NewLinePresenter, wire.Bind(new(ipresenter.ILinePresenter), new(*presenter.LinePresenter)), interactor.NewFavoriteInteractor, wire.Bind(new(usecase.IFavoriteUseCase), new(*interactor.FavoriteInteractor)), interactor.NewSearchInteractor, wire.Bind(new(usecase.ISearchUseCase), new(*interactor.SearchInteractor)), controllers.NewLinebotController, infrastructure.NewRouter)
